//go:build ignore

// Command gen reads the vendored Arlington PDF Model TSVs under testdata/tsv/1.4 and emits
// one Go map literal with one ObjectType entry per TSV file.
//
// Invoke via `go generate ./internal/arlington/...`.
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	tsvDir    = "testdata/tsv/1.4"
	latestDir = "testdata/tsv/latest"
	outFile   = "model_gen.go"
)

// valueTypeIdent maps an Arlington TSV Type token to the matching Go identifier declared in
// arlington.go. Keep in sync with the ValueType const block there.
var valueTypeIdent = map[string]string{
	"array":        "Array",
	"bitmask":      "Bitmask",
	"boolean":      "Boolean",
	"date":         "Date",
	"dictionary":   "Dictionary",
	"integer":      "Integer",
	"matrix":       "Matrix",
	"name":         "Name",
	"name-tree":    "NameTree",
	"null":         "Null",
	"number":       "Number",
	"number-tree":  "NumberTree",
	"rectangle":    "Rectangle",
	"stream":       "Stream",
	"string":       "String",
	"string-ascii": "StringASCII",
	"string-byte":  "StringByte",
	"string-text":  "StringText",
}

// row is one parsed TSV data line, columns in file order.
type row struct {
	key, typ, sinceVersion, deprecatedIn, required, indirectRef,
	inheritable, defaultValue, possibleValues, specialCase, link, note string
}

// linkGroup is the Go source representation of an arlington.LinkGroup literal.
type linkGroup struct {
	valueTypes    []string // Go ValueType identifiers this alternative applies to; nil means "the only alternative"
	candidates    []string
	discriminator string
	byValue       map[string]string // discriminator value -> candidate type name
}

// keyDef is the Go source representation of an arlington.KeyDef literal.
type keyDef struct {
	name              string
	types             []string // Go identifiers, e.g. "Dictionary"
	required          bool
	indirectReference string // Go identifier, e.g. "IndirectEither"
	sinceVersion      string
	deprecatedIn      string
	possibleValues    []string
	linkGroups        []linkGroup
	predicated        bool
	inheritable       bool
}

// typeEntry is one parsed Arlington type (one TSV file), before discriminator resolution.
type typeEntry struct {
	name     string
	keys     []keyDef
	wildcard *keyDef
}

func main() {
	files, err := filepath.Glob(filepath.Join(tsvDir, "*.tsv"))
	if err != nil || len(files) == 0 {
		log.Fatalf("glob %s: %v (found %d files)", tsvDir, err, len(files))
	}
	sort.Strings(files)

	var b strings.Builder
	b.WriteString("// Code generated by gen.go from testdata/tsv/1.4; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Arlington PDF Model data is copyright PDF Association, Inc., Apache-2.0.\n")
	b.WriteString("// See testdata/LICENSE and testdata/README.md for provenance.\n")
	b.WriteString("package arlington\n\n")
	b.WriteString("var Types = map[string]ObjectType{\n")

	post14Keys, err := computePost14Keys()
	if err != nil {
		log.Fatalf("computing post-1.4 keys: %v", err)
	}

	// First pass: parse every type's own keys. keyDefsByType is needed by the second pass to
	// look up each LinkGroup candidate's own schema (its discriminator key, if any).
	var types []typeEntry
	keyDefsByType := map[string][]keyDef{}

	totalRows, simpleRows := 0, 0
	for _, path := range files {
		typeName := strings.TrimSuffix(filepath.Base(path), ".tsv")
		rows, err := parseTSV(path)
		if err != nil {
			log.Fatalf("%s: %v", path, err)
		}

		var keys []keyDef
		var wildcard *keyDef
		for _, r := range rows {
			totalRows++
			kd := buildKeyDef(r)
			if !kd.predicated {
				simpleRows++
			}
			if kd.name == "*" {
				w := kd
				wildcard = &w
				continue
			}
			keys = append(keys, kd)
		}
		types = append(types, typeEntry{name: typeName, keys: keys, wildcard: wildcard})
		keyDefsByType[typeName] = keys
	}

	// Second pass: now that every type's own keys are known, resolve a discriminator for every
	// LinkGroup with more than one candidate.
	for i := range types {
		for j := range types[i].keys {
			resolveDiscriminators(&types[i].keys[j], keyDefsByType)
		}
		if types[i].wildcard != nil {
			resolveDiscriminators(types[i].wildcard, keyDefsByType)
		}
	}

	for _, t := range types {
		fmt.Fprintf(&b, "%q: {\n", t.name)
		fmt.Fprintf(&b, "Name: %q,\n", t.name)
		writeKeysLiteral(&b, "Keys", t.keys)
		if t.wildcard != nil {
			b.WriteString("Wildcard: &KeyDef{\n")
			writeKeyDefFields(&b, *t.wildcard)
			b.WriteString("},\n")
		}
		writeStringSlice(&b, "Post14Keys", post14Keys[t.name])
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	fraction := 0.0
	if totalRows > 0 {
		fraction = float64(simpleRows) / float64(totalRows) * 100
	}
	fmt.Fprintf(os.Stderr, "arlington: %d/%d rows simple (%.1f%%), %d types\n",
		simpleRows, totalRows, fraction, len(files))

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		// Write the unformatted source anyway so it can be inspected for the syntax error.
		_ = os.WriteFile(outFile, []byte(b.String()), 0o644)
		log.Fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", outFile, err)
	}
}

func writeKeysLiteral(b *strings.Builder, field string, keys []keyDef) {
	if len(keys) == 0 {
		return
	}
	fmt.Fprintf(b, "%s: []KeyDef{\n", field)
	for _, kd := range keys {
		b.WriteString("{\n")
		writeKeyDefFields(b, kd)
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
}

func writeKeyDefFields(b *strings.Builder, kd keyDef) {
	fmt.Fprintf(b, "Name: %q,\n", kd.name)
	if len(kd.types) > 0 {
		fmt.Fprintf(b, "Types: []ValueType{%s},\n", strings.Join(kd.types, ", "))
	}
	if kd.required {
		b.WriteString("Required: true,\n")
	}
	if kd.indirectReference != "IndirectEither" {
		fmt.Fprintf(b, "IndirectReference: %s,\n", kd.indirectReference)
	}
	fmt.Fprintf(b, "SinceVersion: %q,\n", kd.sinceVersion)
	if kd.deprecatedIn != "" {
		fmt.Fprintf(b, "DeprecatedIn: %q,\n", kd.deprecatedIn)
	}
	writeStringSlice(b, "PossibleValues", kd.possibleValues)
	writeLinkGroups(b, kd.linkGroups)
	if kd.inheritable {
		b.WriteString("Inheritable: true,\n")
	}
	if kd.predicated {
		b.WriteString("Predicated: true,\n")
	}
}

func writeStringSlice(b *strings.Builder, field string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "%s: []string{", field)
	for i, v := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", v)
	}
	b.WriteString("},\n")
}

func writeLinkGroups(b *strings.Builder, groups []linkGroup) {
	if len(groups) == 0 {
		return
	}
	b.WriteString("LinkGroups: []LinkGroup{\n")
	for _, g := range groups {
		b.WriteString("{\n")
		if len(g.valueTypes) > 0 {
			fmt.Fprintf(b, "ValueTypes: []ValueType{%s},\n", strings.Join(g.valueTypes, ", "))
		}
		writeStringSlice(b, "Candidates", g.candidates)
		if g.discriminator != "" {
			fmt.Fprintf(b, "Discriminator: %q,\n", g.discriminator)
			writeStringMap(b, "ByValue", g.byValue)
		}
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
}

// writeStringMap emits a map[string]string literal with keys in sorted order, so generator
// output stays deterministic (required by TestGeneratorIdempotent).
func writeStringMap(b *strings.Builder, field string, m map[string]string) {
	if len(m) == 0 {
		return
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintf(b, "%s: map[string]string{", field)
	for i, k := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q: %q", k, m[k])
	}
	b.WriteString("},\n")
}

// computePost14Keys returns, per type name (TSV basename), the keys present in testdata/tsv/latest
// but absent from testdata/tsv/1.4 -- i.e. keys the Arlington PDF Model says were introduced
// after PDF 1.4. A type absent from tsv/latest (renamed across versions) is simply omitted,
// which yields an empty, safe (false-negative) Post14Keys for it.
func computePost14Keys() (map[string][]string, error) {
	keys14, err := keySetsByType(tsvDir)
	if err != nil {
		return nil, err
	}
	keysLatest, err := keySetsByType(latestDir)
	if err != nil {
		return nil, err
	}

	post14 := make(map[string][]string, len(keysLatest))
	for typeName, latestKeys := range keysLatest {
		old := keys14[typeName]
		var added []string
		for k := range latestKeys {
			if k == "*" || old[k] {
				continue
			}
			added = append(added, k)
		}
		if len(added) > 0 {
			sort.Strings(added)
			post14[typeName] = added
		}
	}
	return post14, nil
}

// keySetsByType reads every TSV under dir and returns, per type name, the set of Key column
// values (order not preserved; only membership matters). Unlike parseTSV, this only reads the
// first column and tolerates rows with fewer than 12 columns -- tsv/latest, being upstream's
// unfiltered live set, has a handful of vendor-extension rows short a trailing empty column.
func keySetsByType(dir string) (map[string]map[string]bool, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.tsv"))
	if err != nil {
		return nil, err
	}
	out := make(map[string]map[string]bool, len(files))
	for _, path := range files {
		typeName := strings.TrimSuffix(filepath.Base(path), ".tsv")
		f, err := os.Open(path)
		if err != nil {
			return nil, err
		}
		sc := bufio.NewScanner(f)
		sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		set := map[string]bool{}
		first := true
		for sc.Scan() {
			if first {
				first = false // header row
				continue
			}
			line := sc.Text()
			if line == "" {
				continue
			}
			if i := strings.IndexByte(line, '\t'); i >= 0 {
				set[line[:i]] = true
			}
		}
		err = sc.Err()
		f.Close()
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		out[typeName] = set
	}
	return out, nil
}

func parseTSV(path string) ([]row, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var rows []row
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	first := true
	for sc.Scan() {
		if first {
			first = false // header row
			continue
		}
		line := sc.Text()
		if line == "" {
			continue
		}
		cols := strings.Split(line, "\t")
		if len(cols) != 12 {
			return nil, fmt.Errorf("expected 12 columns, got %d: %q", len(cols), line)
		}
		rows = append(rows, row{
			key: cols[0], typ: cols[1], sinceVersion: cols[2], deprecatedIn: cols[3],
			required: cols[4], indirectRef: cols[5], inheritable: cols[6],
			defaultValue: cols[7], possibleValues: cols[8], specialCase: cols[9],
			link: cols[10], note: cols[11],
		})
	}
	return rows, sc.Err()
}

// buildKeyDef converts one TSV row into its Go source representation, classifying the row as
// predicated whenever Required, IndirectReference, or PossibleValues carries an fn: predicate
// this generator does not evaluate.
func buildKeyDef(r row) keyDef {
	kd := keyDef{name: r.key, sinceVersion: r.sinceVersion, deprecatedIn: r.deprecatedIn}

	for _, tok := range strings.Split(r.typ, ";") {
		ident, ok := valueTypeIdent[tok]
		if !ok {
			kd.predicated = true
			continue
		}
		kd.types = append(kd.types, ident)
	}

	switch {
	case r.required == "TRUE":
		kd.required = true
	case strings.Contains(r.required, "fn:"):
		kd.predicated = true
	}

	kd.indirectReference = parseIndirectReference(r.indirectRef)
	if strings.Contains(r.indirectRef, "fn:") {
		kd.predicated = true
	}

	kd.inheritable = r.inheritable == "TRUE"

	if strings.Contains(r.possibleValues, "fn:") {
		kd.predicated = true
	}
	kd.possibleValues = parsePossibleValues(r.possibleValues)
	kd.linkGroups = parseLinkGroups(r.typ, r.link)

	return kd
}

// parseIndirectReference resolves the IndirectReference column to a single IndirectRule.
// The column is a flat scalar (TRUE/FALSE/fn:...) for single-type keys, or bracket-grouped
// per type alternative ("[FALSE];[TRUE]") for multi-type keys; an fn: predicate is always
// flat regardless of type count. FALSE means the value need not be indirect (both direct and
// indirect are legal), not that it must be direct -- that is a separate, always-predicated
// fn:MustBeDirect() column value. So only an all-TRUE column resolves to IndirectRequired;
// every other case (including all-FALSE, and mixed TRUE/FALSE across type alternatives) is
// unconstrained.
func parseIndirectReference(raw string) string {
	if strings.Contains(raw, "fn:") {
		return "IndirectEither"
	}
	groups := splitGroups(raw)
	if len(groups) == 0 {
		return "IndirectEither"
	}
	allTrue := true
	for _, g := range groups {
		if g != "TRUE" {
			allTrue = false
			break
		}
	}
	if allTrue {
		return "IndirectRequired"
	}
	return "IndirectEither"
}

// splitGroups splits a possibly bracket-grouped, ";"-joined column ("[a];[b]") into its
// per-group contents ("a", "b"), or returns the raw value as a single group when unbracketed.
func splitGroups(raw string) []string {
	if raw == "" {
		return nil
	}
	parts := strings.Split(raw, ";")
	out := make([]string, len(parts))
	for i, p := range parts {
		p = strings.TrimPrefix(p, "[")
		p = strings.TrimSuffix(p, "]")
		out[i] = p
	}
	return out
}

// parsePossibleValues flattens the (possibly per-type-grouped) PossibleValues column into a
// single enumerated list, dropping any fn:-predicated entry (a whole-group range constraint
// like fn:Eval(@LW>=0), or a single deprecated/version-gated option mixed into an otherwise
// plain list like fn:Deprecated(1.4,Compatible)).
func parsePossibleValues(raw string) []string {
	if raw == "" {
		return nil
	}
	var out []string
	for _, group := range splitGroups(raw) {
		for _, item := range splitTopLevelComma(group) {
			item = strings.TrimSpace(item)
			if item == "" || strings.HasPrefix(item, "fn:") {
				continue
			}
			item = strings.Trim(item, "'")
			out = append(out, item)
		}
	}
	return out
}

// parseLinkGroups splits typ and link in lockstep, one linkGroup per Type alternative, so a
// key's runtime value (once its Go kind is known) can be resolved to the right subset of
// candidate Arlington types. Falls back to a single, kind-unconditional group covering every
// candidate (the pre-discriminator flattened behavior) when there is only one Type alternative,
// or when the two columns' alternative counts don't line up (a shape this generator doesn't
// expect) -- never guess which alternative a candidate belongs to.
func parseLinkGroups(typ, link string) []linkGroup {
	if link == "" {
		return nil
	}
	linkParts := splitGroups(link)
	typeToks := strings.Split(typ, ";")

	if len(typeToks) <= 1 || len(typeToks) != len(linkParts) {
		var candidates []string
		for _, part := range linkParts {
			candidates = append(candidates, splitNames(part)...)
		}
		if len(candidates) == 0 {
			return nil
		}
		return []linkGroup{{candidates: candidates}}
	}

	var groups []linkGroup
	for i, tok := range typeToks {
		candidates := splitNames(linkParts[i])
		if len(candidates) == 0 {
			continue // this alternative has no sub-schema (e.g. a plain scalar type)
		}
		ident, ok := valueTypeIdent[tok]
		if !ok {
			continue // an unrecognized/predicated type token can't be gated on kind; skip it
		}
		groups = append(groups, linkGroup{valueTypes: []string{ident}, candidates: candidates})
	}
	return groups
}

// splitNames splits one bracket-group's comma-separated Arlington type names.
func splitNames(group string) []string {
	var out []string
	for _, item := range strings.Split(group, ",") {
		item = strings.TrimSpace(item)
		if item != "" {
			out = append(out, item)
		}
	}
	return out
}

// resolveDiscriminators fills in each of kd's LinkGroups' discriminator, if any group has more
// than one candidate. keyDefsByType looks up each candidate's own schema.
func resolveDiscriminators(kd *keyDef, keyDefsByType map[string][]keyDef) {
	for gi := range kd.linkGroups {
		g := &kd.linkGroups[gi]
		if len(g.candidates) < 2 {
			continue
		}
		key, byValue := bestDiscriminator(g.candidates, keyDefsByType)
		if len(byValue) == 0 {
			continue
		}
		g.discriminator = key
		g.byValue = byValue
	}
}

// bestDiscriminator finds the key name that most cleanly disambiguates candidates: a key that
// some candidates declare as Required, non-Predicated, with exactly one PossibleValues entry
// (e.g. AnnotText.Subtype -> [Text], ActionGoTo.S -> [GoTo], FunctionType2.FunctionType -> [2]).
// A candidate that doesn't qualify for the chosen key, or whose value collides with another
// candidate's, is simply absent from the returned map -- partial coverage is safe, since an
// unresolvable candidate is never guessed, just never selected at runtime. Ties (equal
// candidate coverage) break alphabetically by key name, for deterministic generator output.
func bestDiscriminator(candidates []string, keyDefsByType map[string][]keyDef) (string, map[string]string) {
	qualifying := map[string]map[string]string{} // candidate type -> key name -> its one possible value
	keyNameSet := map[string]bool{}
	for _, c := range candidates {
		q := map[string]string{}
		for _, kd := range keyDefsByType[c] {
			if kd.required && !kd.predicated && len(kd.possibleValues) == 1 {
				q[kd.name] = kd.possibleValues[0]
				keyNameSet[kd.name] = true
			}
		}
		qualifying[c] = q
	}

	var keyNames []string
	for k := range keyNameSet {
		keyNames = append(keyNames, k)
	}
	sort.Strings(keyNames)

	var bestKey string
	var bestMap map[string]string
	for _, k := range keyNames {
		byValue := map[string]string{}
		collided := map[string]bool{}
		for _, c := range candidates {
			v, ok := qualifying[c][k]
			if !ok {
				continue
			}
			if existing, taken := byValue[v]; taken && existing != c {
				collided[v] = true
				continue
			}
			byValue[v] = c
		}
		for v := range collided {
			delete(byValue, v)
		}
		if len(byValue) > len(bestMap) {
			bestKey, bestMap = k, byValue
		}
	}
	return bestKey, bestMap
}

// splitTopLevelComma splits s on commas that are not nested inside parentheses, so that
// predicate expressions like "fn:RequiredValue(@V<2,2)" survive as one token.
func splitTopLevelComma(s string) []string {
	var out []string
	depth, start := 0, 0
	for i, r := range s {
		switch r {
		case '(':
			depth++
		case ')':
			depth--
		case ',':
			if depth == 0 {
				out = append(out, s[start:i])
				start = i + 1
			}
		}
	}
	out = append(out, s[start:])
	return out
}
