//go:build ignore

// Command gen reads the vendored Arlington PDF Model TSVs under testdata/tsv/1.4 and emits
// one Go map literal with one ObjectType entry per TSV file.
//
// Invoke via `go generate ./internal/arlington/...`.
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	tsvDir  = "testdata/tsv/1.4"
	outFile = "model_gen.go"
)

// valueTypeIdent maps an Arlington TSV Type token to the matching Go identifier declared in
// arlington.go. Keep in sync with the ValueType const block there.
var valueTypeIdent = map[string]string{
	"array":        "Array",
	"bitmask":      "Bitmask",
	"boolean":      "Boolean",
	"date":         "Date",
	"dictionary":   "Dictionary",
	"integer":      "Integer",
	"matrix":       "Matrix",
	"name":         "Name",
	"name-tree":    "NameTree",
	"null":         "Null",
	"number":       "Number",
	"number-tree":  "NumberTree",
	"rectangle":    "Rectangle",
	"stream":       "Stream",
	"string":       "String",
	"string-ascii": "StringASCII",
	"string-byte":  "StringByte",
	"string-text":  "StringText",
}

// row is one parsed TSV data line, columns in file order.
type row struct {
	key, typ, sinceVersion, deprecatedIn, required, indirectRef,
	inheritable, defaultValue, possibleValues, specialCase, link, note string
}

// keyDef is the Go source representation of an arlington.KeyDef literal.
type keyDef struct {
	name              string
	types             []string // Go identifiers, e.g. "Dictionary"
	required          bool
	indirectReference string // Go identifier, e.g. "IndirectEither"
	sinceVersion      string
	deprecatedIn      string
	possibleValues    []string
	link              []string
	predicated        bool
	inheritable       bool
}

func main() {
	files, err := filepath.Glob(filepath.Join(tsvDir, "*.tsv"))
	if err != nil || len(files) == 0 {
		log.Fatalf("glob %s: %v (found %d files)", tsvDir, err, len(files))
	}
	sort.Strings(files)

	var b strings.Builder
	b.WriteString("// Code generated by gen.go from testdata/tsv/1.4; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Arlington PDF Model data is copyright PDF Association, Inc., Apache-2.0.\n")
	b.WriteString("// See testdata/LICENSE and testdata/README.md for provenance.\n")
	b.WriteString("package arlington\n\n")
	b.WriteString("var Types = map[string]ObjectType{\n")

	totalRows, simpleRows := 0, 0
	for _, path := range files {
		typeName := strings.TrimSuffix(filepath.Base(path), ".tsv")
		rows, err := parseTSV(path)
		if err != nil {
			log.Fatalf("%s: %v", path, err)
		}

		var keys []keyDef
		var wildcard *keyDef
		for _, r := range rows {
			totalRows++
			kd := buildKeyDef(r)
			if !kd.predicated {
				simpleRows++
			}
			if kd.name == "*" {
				w := kd
				wildcard = &w
				continue
			}
			keys = append(keys, kd)
		}

		fmt.Fprintf(&b, "%q: {\n", typeName)
		fmt.Fprintf(&b, "Name: %q,\n", typeName)
		writeKeysLiteral(&b, "Keys", keys)
		if wildcard != nil {
			b.WriteString("Wildcard: &KeyDef{\n")
			writeKeyDefFields(&b, *wildcard)
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	fraction := 0.0
	if totalRows > 0 {
		fraction = float64(simpleRows) / float64(totalRows) * 100
	}
	fmt.Fprintf(os.Stderr, "arlington: %d/%d rows simple (%.1f%%), %d types\n",
		simpleRows, totalRows, fraction, len(files))

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		// Write the unformatted source anyway so it can be inspected for the syntax error.
		_ = os.WriteFile(outFile, []byte(b.String()), 0o644)
		log.Fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", outFile, err)
	}
}

func writeKeysLiteral(b *strings.Builder, field string, keys []keyDef) {
	if len(keys) == 0 {
		return
	}
	fmt.Fprintf(b, "%s: []KeyDef{\n", field)
	for _, kd := range keys {
		b.WriteString("{\n")
		writeKeyDefFields(b, kd)
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
}

func writeKeyDefFields(b *strings.Builder, kd keyDef) {
	fmt.Fprintf(b, "Name: %q,\n", kd.name)
	if len(kd.types) > 0 {
		fmt.Fprintf(b, "Types: []ValueType{%s},\n", strings.Join(kd.types, ", "))
	}
	if kd.required {
		b.WriteString("Required: true,\n")
	}
	if kd.indirectReference != "IndirectEither" {
		fmt.Fprintf(b, "IndirectReference: %s,\n", kd.indirectReference)
	}
	fmt.Fprintf(b, "SinceVersion: %q,\n", kd.sinceVersion)
	if kd.deprecatedIn != "" {
		fmt.Fprintf(b, "DeprecatedIn: %q,\n", kd.deprecatedIn)
	}
	writeStringSlice(b, "PossibleValues", kd.possibleValues)
	writeStringSlice(b, "Link", kd.link)
	if kd.inheritable {
		b.WriteString("Inheritable: true,\n")
	}
	if kd.predicated {
		b.WriteString("Predicated: true,\n")
	}
}

func writeStringSlice(b *strings.Builder, field string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "%s: []string{", field)
	for i, v := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", v)
	}
	b.WriteString("},\n")
}

func parseTSV(path string) ([]row, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var rows []row
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	first := true
	for sc.Scan() {
		if first {
			first = false // header row
			continue
		}
		line := sc.Text()
		if line == "" {
			continue
		}
		cols := strings.Split(line, "\t")
		if len(cols) != 12 {
			return nil, fmt.Errorf("expected 12 columns, got %d: %q", len(cols), line)
		}
		rows = append(rows, row{
			key: cols[0], typ: cols[1], sinceVersion: cols[2], deprecatedIn: cols[3],
			required: cols[4], indirectRef: cols[5], inheritable: cols[6],
			defaultValue: cols[7], possibleValues: cols[8], specialCase: cols[9],
			link: cols[10], note: cols[11],
		})
	}
	return rows, sc.Err()
}

// buildKeyDef converts one TSV row into its Go source representation, classifying the row as
// predicated whenever Required, IndirectReference, or PossibleValues carries an fn: predicate
// this generator does not evaluate.
func buildKeyDef(r row) keyDef {
	kd := keyDef{name: r.key, sinceVersion: r.sinceVersion, deprecatedIn: r.deprecatedIn}

	for _, tok := range strings.Split(r.typ, ";") {
		ident, ok := valueTypeIdent[tok]
		if !ok {
			kd.predicated = true
			continue
		}
		kd.types = append(kd.types, ident)
	}

	switch {
	case r.required == "TRUE":
		kd.required = true
	case strings.Contains(r.required, "fn:"):
		kd.predicated = true
	}

	kd.indirectReference = parseIndirectReference(r.indirectRef)
	if strings.Contains(r.indirectRef, "fn:") {
		kd.predicated = true
	}

	kd.inheritable = r.inheritable == "TRUE"

	if strings.Contains(r.possibleValues, "fn:") {
		kd.predicated = true
	}
	kd.possibleValues = parsePossibleValues(r.possibleValues)
	kd.link = parseGroupedNames(r.link)

	return kd
}

// parseIndirectReference resolves the IndirectReference column to a single IndirectRule.
// The column is a flat scalar (TRUE/FALSE/fn:...) for single-type keys, or bracket-grouped
// per type alternative ("[FALSE];[TRUE]") for multi-type keys; an fn: predicate is always
// flat regardless of type count. Mixed groups (some TRUE, some FALSE) resolve to Either,
// since the requirement depends on which type alternative applies.
func parseIndirectReference(raw string) string {
	if strings.Contains(raw, "fn:") {
		return "IndirectEither"
	}
	groups := splitGroups(raw)
	if len(groups) == 0 {
		return "IndirectEither"
	}
	allTrue, allFalse := true, true
	for _, g := range groups {
		switch g {
		case "TRUE":
			allFalse = false
		case "FALSE":
			allTrue = false
		default:
			allTrue, allFalse = false, false
		}
	}
	switch {
	case allTrue:
		return "IndirectRequired"
	case allFalse:
		return "IndirectForbidden"
	default:
		return "IndirectEither"
	}
}

// splitGroups splits a possibly bracket-grouped, ";"-joined column ("[a];[b]") into its
// per-group contents ("a", "b"), or returns the raw value as a single group when unbracketed.
func splitGroups(raw string) []string {
	if raw == "" {
		return nil
	}
	parts := strings.Split(raw, ";")
	out := make([]string, len(parts))
	for i, p := range parts {
		p = strings.TrimPrefix(p, "[")
		p = strings.TrimSuffix(p, "]")
		out[i] = p
	}
	return out
}

// parsePossibleValues flattens the (possibly per-type-grouped) PossibleValues column into a
// single enumerated list, dropping any fn:-predicated entry (a whole-group range constraint
// like fn:Eval(@LW>=0), or a single deprecated/version-gated option mixed into an otherwise
// plain list like fn:Deprecated(1.4,Compatible)).
func parsePossibleValues(raw string) []string {
	if raw == "" {
		return nil
	}
	var out []string
	for _, group := range splitGroups(raw) {
		for _, item := range splitTopLevelComma(group) {
			item = strings.TrimSpace(item)
			if item == "" || strings.HasPrefix(item, "fn:") {
				continue
			}
			out = append(out, item)
		}
	}
	return out
}

// parseGroupedNames flattens a (possibly per-type-grouped) comma-separated Link column into a
// single list of Arlington type names.
func parseGroupedNames(raw string) []string {
	if raw == "" {
		return nil
	}
	var out []string
	for _, group := range splitGroups(raw) {
		for _, item := range strings.Split(group, ",") {
			item = strings.TrimSpace(item)
			if item != "" {
				out = append(out, item)
			}
		}
	}
	return out
}

// splitTopLevelComma splits s on commas that are not nested inside parentheses, so that
// predicate expressions like "fn:RequiredValue(@V<2,2)" survive as one token.
func splitTopLevelComma(s string) []string {
	var out []string
	depth, start := 0, 0
	for i, r := range s {
		switch r {
		case '(':
			depth++
		case ')':
			depth--
		case ',':
			if depth == 0 {
				out = append(out, s[start:i])
				start = i + 1
			}
		}
	}
	out = append(out, s[start:])
	return out
}
